// services/bookIngestionService.ts

import { httpsCallable } from 'firebase/functions';
import { getFirebaseFunctions } from '../lib/firebase.ts';
// FIX: Added import of Book type to support the new ensureBookExists method.
import { Book } from '../types/entities.ts';

/**
 * BookIngestionService
 * 🔒 SINGLE AUTHORITY for triggering server-side book materialization.
 *
 * HARD RULES:
 * - Owns httpsCallable('ingestBook')
 * - Enforces payload contract
 * - Returns canonical identifiers
 * - Never throws (UX must not dead-end)
 */

export type BookIngestionParams = {
  bookId: string;
  source: 'googleBooks' | 'openLibrary';
  rawBook: any;
};

export type BookIngestionResult = {
  bookId: string;
  editionId?: string;
  status?: string;
};

export const bookIngestionService = {
  /**
   * ingest
   * Implementation of BOOK_INGESTION_CONTRACT_V1
   *
   * @returns BookIngestionResult | null
   * Canonical identifiers generated by the backend.
   */
  async ingest(
    params: BookIngestionParams
  ): Promise<BookIngestionResult | null> {
    try {
      const functions = getFirebaseFunctions();
      const ingestFn = httpsCallable(functions, 'ingestBook');

      const result = await ingestFn({
        bookId: params.bookId,
        source: params.source,
        rawBook: params.rawBook,
      });

      /**
       * Defensive contract validation
       * Backend MAY return:
       * { bookId }
       * { bookId, editionId }
       * { bookId, status }
       */
      const data = result?.data as Partial<BookIngestionResult> | undefined;

      if (data?.bookId) {
        return {
          bookId: data.bookId,
          editionId: data.editionId,
          status: data.status,
        };
      }

      console.warn(
        '[INGESTION_SERVICE][INVALID_RESPONSE]',
        data
      );
      return null;
    } catch (error) {
      /**
       * Functional Requirement:
       * - Must not block navigation
       * - Must not throw
       * - Must log clearly
       */
      console.warn(
        '[INGESTION_SERVICE][FAILURE]',
        error
      );
      return null;
    }
  },

  // FIX: Added ensureBookExists method to handle conditional ingestion as required by shelfActions.ts
  /**
   * ensureBookExists
   * High-level orchestrator that checks if a book needs ingestion
   * before local persistence operations.
   */
  async ensureBookExists(params: { bookId: string; bookHint?: Book }): Promise<void> {
    const { bookId, bookHint } = params;
    const isExternal = bookId.startsWith('gb_') || bookId.startsWith('ol_');

    if (isExternal && bookHint) {
      const source = bookId.startsWith('gb_') ? 'googleBooks' : 'openLibrary';
      await this.ingest({
        bookId,
        source: source as any,
        rawBook: bookHint,
      });
    }
  },
};