// services/bookIngestionService.ts

import { Book } from '../types/entities.ts';
import {
  ensureCanonicalBook,
  EnsureCanonicalBookResult,
} from '../lib/books/ensureCanonicalBook.ts';

/**
 * BookIngestionService
 * 🔒 SINGLE AUTHORITY for triggering server-side book materialization.
 *
 * HARD RULES:
 * - Delegates canonical resolution to ensureCanonicalBook()
 * - Enforces payload contract
 * - Returns canonical identifiers
 * - Never throws (UX must not dead-end)
 */

export type BookIngestionParams = {
  providerExternalId: string;
  source: 'googleBooks' | 'openLibrary';
  rawBook: any;
};

export type BookIngestionResult = {
  canonicalBookId: string;
  bookId: string;
  editionId?: string;
  status?: string;
};

const normalizeIngestionSource = (
  source: unknown
): 'googleBooks' | 'openLibrary' | null => {
  const value = String(source || '').trim();

  if (
    value === 'googleBooks' ||
    value === 'google_books' ||
    value === 'googlebooks' ||
    value === 'GOOGLE_BOOKS'
  ) {
    return 'googleBooks';
  }

  if (
    value === 'openLibrary' ||
    value === 'open_library' ||
    value === 'openlibrary' ||
    value === 'OPEN_LIBRARY'
  ) {
    return 'openLibrary';
  }

  return null;
};

export const bookIngestionService = {
  /**
   * ingest
   * Implementation of BOOK_INGESTION_CONTRACT_V1
   *
   * @returns BookIngestionResult | null
   * Canonical identifiers generated by the backend.
   */
  async ingest(
    params: BookIngestionParams
  ): Promise<BookIngestionResult | null> {
    const source = normalizeIngestionSource(params.source);
    if (!source) {
      console.warn('[INGESTION_SERVICE][INVALID_SOURCE]', params.source);
      return null;
    }

    const result = await ensureCanonicalBook({
      providerExternalId: params.providerExternalId,
      source,
      rawBook: params.rawBook,
    });

    if (!result) {
      return null;
    }

    return result as EnsureCanonicalBookResult;
  },

  /**
   * ensureBookExists
   * Enforces V2 ingestion boundary:
   * external IDs are not ingested from shelf actions.
   */
  async ensureBookExists(params: { bookId: string; bookHint?: Book }): Promise<void> {
    const { bookId } = params;
    const isExternal = bookId.startsWith('gb_') || bookId.startsWith('ol_');

    if (isExternal) {
      throw new Error('EXTERNAL_BOOK_REQUIRES_DETAILS_INGESTION');
    }
  },
};
