import { wrapCallableV2 } from "../contracts/wrapCallableV2";
import { createWriteProject as createWriteProjectRaw } from "../createWriteProject";
import { deleteWriteProject as deleteWriteProjectRaw } from "../deleteWriteProject";
import { updateWriteProject as updateWriteProjectRaw } from "../updateWriteProject";
import { applyWriteChunkMutation as applyWriteChunkMutationRaw } from "../applyWriteChunkMutation";
import { compactWriteOperationLogs as compactWriteOperationLogsRaw } from "../compactWriteOperationLogs";
import { publishWriteCollaborationOperation as publishWriteCollaborationOperationRaw } from "../publishWriteCollaborationOperation";
import { syncWriteCollaborationReplayCursor as syncWriteCollaborationReplayCursorRaw } from "../syncWriteCollaborationReplayCursor";
import { syncWriteCollaborationPresence as syncWriteCollaborationPresenceRaw } from "../syncWriteCollaborationPresence";
import { duplicateWriteProject as duplicateWriteProjectRaw } from "../duplicateWriteProject";
import { publishWriteProject as publishWriteProjectRaw } from "../publishWriteProject";
import { createProjectRelease as createProjectReleaseRaw } from "../createProjectRelease";
import { generateProjectReleaseEpub as generateProjectReleaseEpubRaw } from "../generateProjectReleaseEpub";
import { bridgeReleaseToCanonicalBook as bridgeReleaseToCanonicalBookRaw } from "../bridgeReleaseToCanonicalBook";
import { updatePublishedBookRights as updatePublishedBookRightsRaw } from "../updatePublishedBookRights";
import { bridgeReleaseToLongformPublication as bridgeReleaseToLongformPublicationRaw } from "../bridgeReleaseToLongformPublication";
import { getProjectPublicationSettings as getProjectPublicationSettingsRaw } from "../getProjectPublicationSettings";
import { updateLongformPublicationVisibility as updateLongformPublicationVisibilityRaw } from "../updateLongformPublicationVisibility";
import { updatePublishedBookVisibility as updatePublishedBookVisibilityRaw } from "../updatePublishedBookVisibility";
import { getProjectReleasePreview as getProjectReleasePreviewRaw } from "../getProjectReleasePreview";
import { getProjectReleaseEbookPreviewSession as getProjectReleaseEbookPreviewSessionRaw } from "../getProjectReleaseEbookPreviewSession";
import { getLongformPublication as getLongformPublicationRaw } from "../getLongformPublication";
import { getAccessibleBook as getAccessibleBookRaw } from "../getAccessibleBook";
import { getRelatedBooks as getRelatedBooksRaw } from "../catalog/getRelatedBooks";
import { getRecommendations as getRecommendationsRaw } from "../catalog/getRecommendations";
import { listOwnLongformPublications as listOwnLongformPublicationsRaw } from "../listOwnLongformPublications";
import { createWriteProjectShareLink as createWriteProjectShareLinkRaw } from "../createWriteProjectShareLink";
import { revokeWriteProjectShareLink as revokeWriteProjectShareLinkRaw } from "../revokeWriteProjectShareLink";

export const createWriteProject = wrapCallableV2("createWriteProject", createWriteProjectRaw);
export const deleteWriteProject = wrapCallableV2("deleteWriteProject", deleteWriteProjectRaw);
export const updateWriteProject = wrapCallableV2("updateWriteProject", updateWriteProjectRaw);
export const applyWriteChunkMutation = wrapCallableV2("applyWriteChunkMutation", applyWriteChunkMutationRaw);
export const compactWriteOperationLogs = wrapCallableV2("compactWriteOperationLogs", compactWriteOperationLogsRaw);
export const publishWriteCollaborationOperation = wrapCallableV2("publishWriteCollaborationOperation", publishWriteCollaborationOperationRaw);
export const syncWriteCollaborationReplayCursor = wrapCallableV2("syncWriteCollaborationReplayCursor", syncWriteCollaborationReplayCursorRaw);
export const syncWriteCollaborationPresence = wrapCallableV2("syncWriteCollaborationPresence", syncWriteCollaborationPresenceRaw);
export const duplicateWriteProject = wrapCallableV2("duplicateWriteProject", duplicateWriteProjectRaw);
export const publishWriteProject = wrapCallableV2("publishWriteProject", publishWriteProjectRaw);
export const createProjectRelease = wrapCallableV2("createProjectRelease", createProjectReleaseRaw);
export const generateProjectReleaseEpub = wrapCallableV2("generateProjectReleaseEpub", generateProjectReleaseEpubRaw);
export const bridgeReleaseToCanonicalBook = wrapCallableV2("bridgeReleaseToCanonicalBook", bridgeReleaseToCanonicalBookRaw);
export const updatePublishedBookRights = wrapCallableV2("updatePublishedBookRights", updatePublishedBookRightsRaw);
export const getProjectPublicationSettings = wrapCallableV2("getProjectPublicationSettings", getProjectPublicationSettingsRaw);
export const updateLongformPublicationVisibility = wrapCallableV2("updateLongformPublicationVisibility", updateLongformPublicationVisibilityRaw);
export const updatePublishedBookVisibility = wrapCallableV2("updatePublishedBookVisibility", updatePublishedBookVisibilityRaw);
export const bridgeReleaseToLongformPublication = wrapCallableV2("bridgeReleaseToLongformPublication", bridgeReleaseToLongformPublicationRaw);
export const getProjectReleasePreview = wrapCallableV2("getProjectReleasePreview", getProjectReleasePreviewRaw);
export const getProjectReleaseEbookPreviewSession = wrapCallableV2("getProjectReleaseEbookPreviewSession", getProjectReleaseEbookPreviewSessionRaw);
export const getLongformPublication = wrapCallableV2("getLongformPublication", getLongformPublicationRaw);
export const getAccessibleBook = wrapCallableV2("getAccessibleBook", getAccessibleBookRaw);
export const getRelatedBooks = wrapCallableV2("getRelatedBooks", getRelatedBooksRaw);
export const getRecommendations = wrapCallableV2("getRecommendations", getRecommendationsRaw);
export const listOwnLongformPublications = wrapCallableV2("listOwnLongformPublications", listOwnLongformPublicationsRaw);
export const createWriteProjectShareLink = wrapCallableV2("createWriteProjectShareLink", createWriteProjectShareLinkRaw);
export const revokeWriteProjectShareLink = wrapCallableV2("revokeWriteProjectShareLink", revokeWriteProjectShareLinkRaw);
