import type { CSSProperties } from 'react';

export const socialFeedLayout = {
    railWidthPx: 648,
    estimatedPostHeightPx: 560,
    overscanPx: 1600,
    fetchAheadPx: 1800,
    postGapPx: 14,
    separatorSpacePx: 12,
    separatorInsetPx: 16,
    separatorInsetDesktopPx: 20,
    postInlinePadding: '1rem',
    postInlinePaddingDesktop: '1.25rem',
    postBlockPadding: '1rem',
    postBlockPaddingDesktop: '1.25rem',
    postSectionGap: '1rem',
    postSectionGapCompact: '0.75rem',
    postActionPaddingBottom: '0.75rem',
    postActionMarginTop: '0.875rem',
    postActionPaddingTop: '0.625rem',
    postActionBorder: 'rgba(255,255,255,0.07)',
    postActionHoverBackground: 'rgba(255,255,255,0.055)',
    postActionActiveBackground: 'rgba(255,255,255,0.075)',
    postActionSelectedBackground: 'rgba(255,255,255,0.06)',
    postActionTransitionMs: 150,
    cardRadius: '1rem',
    cardBackground: 'linear-gradient(180deg, rgba(255, 255, 255, 0.034), rgba(255, 255, 255, 0.014))',
    cardBorder: 'rgba(255, 255, 255, 0.095)',
    cardShadow: '0 1px 0 rgba(255,255,255,0.035) inset, 0 18px 42px -40px rgba(0,0,0,0.86)',
    cardWash: 'radial-gradient(circle at top, rgba(0,119,182,0.06), transparent 58%)',
    fabSize: '3rem',
    fabIconSize: '1.125rem',
    fabBottomOffset: '1rem',
    fabBackground: '#1d9bf0',
    fabHoverBackground: '#1a8cd8',
    fabBorder: 'rgba(124, 200, 255, 0.26)',
    fabShadow: '0 8px 18px rgba(8,53,92,0.22)',
    fabTransitionMs: 150,
} as const;

export const socialFeedLayoutStyle = {
    '--social-rail-v23': `${socialFeedLayout.railWidthPx}px`,
    '--social-rail-width': `${socialFeedLayout.railWidthPx}px`,
    '--social-feed-post-gap': `${socialFeedLayout.postGapPx}px`,
    '--social-feed-separator-space': `${socialFeedLayout.separatorSpacePx}px`,
    '--social-feed-separator-inset': `${socialFeedLayout.separatorInsetPx}px`,
    '--social-feed-separator-inset-md': `${socialFeedLayout.separatorInsetDesktopPx}px`,
    '--social-post-inline-padding': socialFeedLayout.postInlinePadding,
    '--social-post-inline-padding-md': socialFeedLayout.postInlinePaddingDesktop,
    '--social-post-block-padding': socialFeedLayout.postBlockPadding,
    '--social-post-block-padding-md': socialFeedLayout.postBlockPaddingDesktop,
    '--social-post-section-gap': socialFeedLayout.postSectionGap,
    '--social-post-section-gap-compact': socialFeedLayout.postSectionGapCompact,
    '--social-post-action-padding-bottom': socialFeedLayout.postActionPaddingBottom,
    '--social-post-action-margin-top': socialFeedLayout.postActionMarginTop,
    '--social-post-action-padding-top': socialFeedLayout.postActionPaddingTop,
    '--social-post-action-border': socialFeedLayout.postActionBorder,
    '--social-post-action-hover-bg': socialFeedLayout.postActionHoverBackground,
    '--social-post-action-active-bg': socialFeedLayout.postActionActiveBackground,
    '--social-post-action-selected-bg': socialFeedLayout.postActionSelectedBackground,
    '--social-post-action-transition': `${socialFeedLayout.postActionTransitionMs}ms`,
    '--social-post-card-radius': socialFeedLayout.cardRadius,
    '--social-post-card-bg': socialFeedLayout.cardBackground,
    '--social-post-card-border': socialFeedLayout.cardBorder,
    '--social-post-card-shadow': socialFeedLayout.cardShadow,
    '--social-post-card-wash': socialFeedLayout.cardWash,
    '--social-fab-size': socialFeedLayout.fabSize,
    '--social-fab-icon-size': socialFeedLayout.fabIconSize,
    '--social-fab-bottom-offset': socialFeedLayout.fabBottomOffset,
    '--social-fab-bg': socialFeedLayout.fabBackground,
    '--social-fab-hover-bg': socialFeedLayout.fabHoverBackground,
    '--social-fab-border': socialFeedLayout.fabBorder,
    '--social-fab-shadow': socialFeedLayout.fabShadow,
    '--social-fab-transition': `${socialFeedLayout.fabTransitionMs}ms`,
} as CSSProperties;
