import {
  evaluateProjectionCertification,
  MAX_RECOVERY_RUNTIME_SECONDS,
  type ProjectionCertificationGateResult,
  type ProjectionCertificationStatus,
  type ProjectionClassification,
  type ProjectionDefinition,
  type ProjectionHealth,
  type ProjectionMaintainer,
} from "./projectionRecoveryControlPlane";

export type RegisteredProjectionDefinition = ProjectionDefinition & {
  recoveryGaps: string[];
  notes: string;
};

export type ProjectionCertificationReport = {
  total: number;
  statusBreakdown: Record<ProjectionCertificationStatus, number>;
  productionReady: string[];
  betaReady: string[];
  notReady: string[];
  deprecated: string[];
  failingProductionRequired: ProjectionCertificationGateResult[];
  topRemainingGaps: Array<{
    requirement: string;
    count: number;
    projections: string[];
  }>;
};

const DEFAULT_MAX_BATCH_SIZE = 100;
const DEFAULT_REQUIRED_RUNTIME_SECONDS = MAX_RECOVERY_RUNTIME_SECONDS;
const RUNBOOK_ROOT = "docs/operations/projections";

function defineProjection(input: {
  projectionName: string;
  classification: ProjectionClassification;
  authoritySources: string[];
  projectionCollections: string[];
  maintainer: ProjectionMaintainer;
  currentConsumers: string[];
  currentCertificationStatus: ProjectionCertificationStatus;
  requiredCertificationStatus?: ProjectionCertificationStatus;
  rebuildSupported?: boolean;
  verificationSupported?: boolean;
  reconciliationSupported?: boolean;
  failureLedgerSupported?: boolean;
  dryRunSupported?: boolean;
  checkpointSupported?: boolean;
  structuredReportingSupported?: boolean;
  idempotent?: boolean;
  restartable?: boolean;
  requiredIndexes?: string[];
  runbookPath?: string | null;
  recoveryGaps: string[];
  notes: string;
}): RegisteredProjectionDefinition {
  return {
    projectionName: input.projectionName,
    classification: input.classification,
    authoritySources: input.authoritySources,
    projectionCollections: input.projectionCollections,
    maintainer: input.maintainer,
    currentConsumers: input.currentConsumers,
    rebuildSupported: input.rebuildSupported ?? false,
    verificationSupported: input.verificationSupported ?? false,
    reconciliationSupported: input.reconciliationSupported ?? false,
    failureLedgerSupported: input.failureLedgerSupported ?? false,
    dryRunSupported: input.dryRunSupported ?? false,
    checkpointSupported: input.checkpointSupported ?? false,
    structuredReportingSupported: input.structuredReportingSupported ?? false,
    idempotent: input.idempotent ?? false,
    restartable: input.restartable ?? false,
    destructiveRebuildAllowed: false,
    maxBatchSize: DEFAULT_MAX_BATCH_SIZE,
    maxRuntimeSeconds: DEFAULT_REQUIRED_RUNTIME_SECONDS,
    requiredIndexes: input.requiredIndexes ?? [],
    runbookPath: input.runbookPath ?? null,
    currentCertificationStatus: input.currentCertificationStatus,
    requiredCertificationStatus:
      input.requiredCertificationStatus ?? "production_ready",
    recoveryGaps: input.recoveryGaps,
    notes: input.notes,
  };
}

const quoteProjectionBase = {
  classification: "fanout_projection" as const,
  authoritySources: ["quotes/{quoteId}"],
  maintainer: "hybrid" as const,
  currentConsumers: [
    "quote APIs",
    "social composer quote attachments",
    "quote discovery",
  ],
  currentCertificationStatus: "production_ready" as const,
  rebuildSupported: true,
  verificationSupported: true,
  failureLedgerSupported: true,
  dryRunSupported: true,
  checkpointSupported: true,
  structuredReportingSupported: true,
  idempotent: true,
  restartable: true,
  requiredIndexes: ["quotes(__name__)", "quotes(authorUid,__name__)", "quotes(ownerId,__name__)", "quotes(bookId,__name__)"],
  runbookPath: `${RUNBOOK_ROOT}/QuoteProjectionRecoveryRunbook.md`,
  recoveryGaps: [],
  notes: "Quote projection recovery is implemented through the Phase 8A recovery control plane.",
};

const reviewProjectionBase = {
  classification: "fanout_projection" as const,
  authoritySources: ["reviews/{reviewId}"],
  maintainer: "hybrid" as const,
  currentConsumers: [
    "listBookReviews",
    "profile review hydration",
    "social review surfaces",
  ],
  currentCertificationStatus: "production_ready" as const,
  rebuildSupported: true,
  verificationSupported: true,
  failureLedgerSupported: true,
  dryRunSupported: true,
  checkpointSupported: true,
  structuredReportingSupported: true,
  idempotent: true,
  restartable: true,
  requiredIndexes: ["reviews(__name__)", "reviews(uid,__name__)", "reviews(userId,__name__)", "reviews(bookId,__name__)"],
  runbookPath: `${RUNBOOK_ROOT}/ReviewProjectionRecoveryRunbook.md`,
  recoveryGaps: [],
  notes: "Review projection recovery is implemented through the Phase 8A recovery control plane.",
};

const searchProjectionBase = {
  classification: "search_projection" as const,
  maintainer: "hybrid" as const,
  currentCertificationStatus: "production_ready" as const,
  rebuildSupported: true,
  verificationSupported: true,
  reconciliationSupported: true,
  failureLedgerSupported: true,
  dryRunSupported: true,
  checkpointSupported: true,
  structuredReportingSupported: true,
  idempotent: true,
  restartable: true,
  recoveryGaps: [],
  notes: "Search projection recovery is implemented through the Phase 8A recovery control plane.",
};

export const PROJECTION_REGISTRY_ENTRIES: RegisteredProjectionDefinition[] = [
  defineProjection({
    ...quoteProjectionBase,
    projectionName: "user_quotes",
    projectionCollections: ["user_quotes"],
  }),
  defineProjection({
    ...quoteProjectionBase,
    projectionName: "book_quote_projection",
    projectionCollections: ["book_quote_projection"],
  }),
  defineProjection({
    ...quoteProjectionBase,
    projectionName: "social_quote_projection",
    projectionCollections: ["social_quote_projection"],
  }),
  defineProjection({
    ...reviewProjectionBase,
    projectionName: "user_reviews",
    projectionCollections: ["user_reviews"],
  }),
  defineProjection({
    ...reviewProjectionBase,
    projectionName: "book_review_projection",
    projectionCollections: ["book_review_projection"],
  }),
  defineProjection({
    ...reviewProjectionBase,
    projectionName: "social_review_projection",
    projectionCollections: ["social_review_projection"],
  }),
  defineProjection({
    projectionName: "legacy_user_reviews_projection",
    classification: "compatibility_projection",
    authoritySources: ["books/{bookId}/reviews/{reviewId}"],
    projectionCollections: ["user_reviews"],
    maintainer: "manual_rebuild",
    currentConsumers: ["profile compatibility reads"],
    currentCertificationStatus: "deprecated",
    requiredCertificationStatus: "deprecated",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["collectionGroup(reviews).where(userId==uid)"],
    runbookPath: `${RUNBOOK_ROOT}/LegacyUserReviewsProjectionDeprecationRunbook.md`,
    recoveryGaps: [],
    notes: "Deprecated behind canonical reviews/{reviewId} and certified review fanout projections; retained only for import/runtime compatibility.",
  }),
  defineProjection({
    projectionName: "notification_summary",
    classification: "aggregate_projection",
    authoritySources: ["notifications/{notificationId}", "activity_log"],
    projectionCollections: ["notification_summary", "users/{uid}/meta/unread"],
    maintainer: "hybrid",
    currentConsumers: ["notification feed", "unread badges"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["notifications(__name__)", "notifications(uid)", "notification_summary(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/NotificationSummaryRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Notification summary recovery recomputes aggregate truth from canonical notifications through the Phase 8A recovery control plane.",
  }),
  defineProjection({
    projectionName: "event_stats",
    classification: "aggregate_projection",
    authoritySources: ["events/{eventId}/rsvps/{userId}"],
    projectionCollections: ["event_stats"],
    maintainer: "hybrid",
    currentConsumers: ["event stats public read surface"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["events(__name__)", "event_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/EventStatsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Event Stats recovery recomputes exact RSVP counts from events/{eventId}/rsvps/{userId}; runtime triggers, admin backfill, and repair all emit the canonical event_stats schema. venue_stats remains deprecated and excluded.",
  }),
  defineProjection({
    ...searchProjectionBase,
    projectionName: "search_feed",
    authoritySources: ["posts", "post_stats"],
    projectionCollections: ["search_feed"],
    currentConsumers: ["social search", "discovery feed search"],
    requiredIndexes: ["posts(__name__)", "posts(authorId,__name__)", "post_stats(__name__)", "search_feed(__name__)", "search_feed(status,visibility,createdAt)"],
    runbookPath: `${RUNBOOK_ROOT}/SearchFeedRecoveryRunbook.md`,
  }),
  defineProjection({
    ...searchProjectionBase,
    projectionName: "search_bookmarks",
    authoritySources: [
      "users/{uid}/bookmarks",
      "users/{uid}/venue_bookmarks",
      "users/{uid}/event_bookmarks",
    ],
    projectionCollections: ["search_bookmarks"],
    currentConsumers: ["search personalization", "bookmark filters"],
    requiredIndexes: ["collectionGroup(bookmarks)", "search_bookmarks(__name__)", "search_bookmarks(uid,entityType,createdAt)"],
    runbookPath: `${RUNBOOK_ROOT}/SearchBookmarksRecoveryRunbook.md`,
  }),
  defineProjection({
    ...searchProjectionBase,
    projectionName: "search_notifications",
    authoritySources: ["notifications/{id}"],
    projectionCollections: ["search_notifications"],
    currentConsumers: ["notification search", "admin notification search"],
    requiredIndexes: ["notifications(__name__)", "notifications(uid)", "search_notifications(__name__)", "search_notifications(uid,read,createdAt)"],
    runbookPath: `${RUNBOOK_ROOT}/SearchNotificationsRecoveryRunbook.md`,
  }),
  defineProjection({
    projectionName: "user_library_books",
    classification: "aggregate_projection",
    authoritySources: ["shelf_books", "reading_progress"],
    projectionCollections: ["user_library_books"],
    maintainer: "hybrid",
    currentConsumers: ["library", "profile", "search", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "user_library_books(uid,updatedAt)",
      "shelf_books(__name__)",
      "shelf_books(ownerId,__name__)",
      "shelf_books(bookId,__name__)",
      "shelf_books(ownerId,bookId)",
      "reading_progress(__name__)",
      "reading_progress(uid,__name__)",
      "reading_progress(userId,__name__)",
      "reading_progress(bookId,__name__)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/UserLibraryRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "User library recovery deterministically recomputes bounded uid/book pairs from shelf_books and reading_progress through the Phase 8A recovery control plane.",
  }),
  defineProjection({
    projectionName: "book_stats",
    classification: "aggregate_projection",
    authoritySources: ["reviews/{reviewId}"],
    projectionCollections: ["book_stats"],
    maintainer: "hybrid",
    currentConsumers: ["book cards", "review APIs", "search ranking"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reviews(bookId,status,visibility,__name__)", "book_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/BookStatsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Book Stats recovery recomputes exact review and rating counters from reviews/{reviewId}. Legacy book-scoped reviews and ratings remain compatibility-only and are excluded from certification authority.",
  }),
  defineProjection({
    projectionName: "book_catalog_counter_projection",
    classification: "compatibility_projection",
    authoritySources: ["reviews/{reviewId}"],
    projectionCollections: [
      "books.rating",
      "books.ratingsCount",
      "books.reviewCount",
      "books.reviewsCount",
    ],
    maintainer: "hybrid",
    currentConsumers: ["home discovery", "recommendations", "book cards", "AI book context"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reviews(bookId,status,visibility,__name__)", "books(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/BookStatsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Catalog counter compatibility fields are repaired by recoverBookStats from canonical reviews without changing ranking behavior.",
  }),
  defineProjection({
    projectionName: "social_user_stats",
    classification: "aggregate_projection",
    authoritySources: [
      "users/{targetUid}/followers/{followerUid}",
      "users/{followerUid}/following/{targetUid}",
    ],
    projectionCollections: ["user_stats.followers", "user_stats.following"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "profile stats callable", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "users(__name__)",
      "users/{uid}/followers(__name__)",
      "users/{uid}/following(__name__)",
      "user_stats(__name__)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/FollowGraphRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Follow graph recovery validates canonical mirror schema and reconciles social user stats from users/*/followers and users/*/following.",
  }),
  defineProjection({
    projectionName: "library_user_stats",
    classification: "aggregate_projection",
    authoritySources: ["user_library_books"],
    projectionCollections: ["user_stats.libraryBooks", "user_stats.counters.totalBooks"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "user_stats(__name__)", "user_library_books(uid)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Library user stats are recovered from certified user_library_books into the user_stats compatibility envelope.",
  }),
  defineProjection({
    projectionName: "shelf_user_stats",
    classification: "aggregate_projection",
    authoritySources: ["shelves"],
    projectionCollections: ["user_stats.shelvesCreated", "user_stats.counters.totalShelves"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "user_stats(__name__)", "shelves(ownerId,isVirtual)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Shelf user stats count non-virtual shelves per owner and write compatibility fields on user_stats.",
  }),
  defineProjection({
    projectionName: "content_user_stats",
    classification: "aggregate_projection",
    authoritySources: ["posts", "reviews", "quotes"],
    projectionCollections: ["user_stats.posts", "user_stats.reviews", "user_stats.quotes"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "admin", "profile quality stats"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "posts(authorId)", "reviews(uid,status)", "quotes(ownerId)", "quotes(authorUid)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Content user stats count posts, active reviews, and quotes into the user_stats compatibility envelope.",
  }),
  defineProjection({
    projectionName: "writing_user_stats",
    classification: "aggregate_projection",
    authoritySources: ["users/{uid}/projects"],
    projectionCollections: ["user_stats.projects", "user_stats.wordsWritten"],
    maintainer: "hybrid",
    currentConsumers: ["profile quality stats", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "users/{uid}/projects(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Writing user stats count user-owned write projects and stored word counters.",
  }),
  defineProjection({
    projectionName: "profile_quality_stats",
    classification: "aggregate_projection",
    authoritySources: ["users", "certified domain stats"],
    projectionCollections: ["user_stats.profileCompletionScore", "user_stats.pcsVersion"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "matchmaker"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "user_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Profile quality stats recompute the existing profile completion score from user profile fields and certified domain stats.",
  }),
  defineProjection({
    projectionName: "storage_user_stats",
    classification: "aggregate_projection",
    authoritySources: ["attachments", "storage_metadata"],
    projectionCollections: ["user_stats.storageUsageBytes", "user_stats.attachmentStorageFiles"],
    maintainer: "hybrid",
    currentConsumers: ["admin", "quota checks"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "attachments(uploader.uid)", "user_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Storage user stats recompute attachment file count and byte usage from attachment metadata.",
  }),
  defineProjection({
    projectionName: "user_stats",
    classification: "compatibility_projection",
    authoritySources: [
      "library_user_stats",
      "shelf_user_stats",
      "content_user_stats",
      "writing_user_stats",
      "profile_quality_stats",
      "storage_user_stats",
      "social_user_stats",
    ],
    projectionCollections: ["user_stats"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "admin"],
    currentCertificationStatus: "deprecated",
    requiredCertificationStatus: "deprecated",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["user_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/UserStatsDomainRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "user_stats is a compatibility envelope only. It must not be certified as one aggregate projection.",
  }),
  defineProjection({
    projectionName: "post_engagement_stats",
    classification: "aggregate_projection",
    authoritySources: [
      "users/{uid}/likes/{postId}",
      "users/{uid}/reposts/{postId}",
      "users/{uid}/bookmarks/{entityId}[type=post]",
      "posts/{postId}/comments/{commentId}",
    ],
    projectionCollections: ["post_stats", "posts.counters"],
    maintainer: "hybrid",
    currentConsumers: ["feeds", "social cards", "search ranking"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "posts(__name__)",
      "posts(authorId,__name__)",
      "post_stats(__name__)",
      "collectionGroup(likes).where(postId==postId)",
      "collectionGroup(reposts).where(originalPostId==postId)",
      "collectionGroup(bookmarks).where(entityId==postId,type==post)",
      "posts/{postId}/comments(__name__)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/PostEngagementRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Post engagement stats recovery recomputes exact counters from user-centric likes/reposts/bookmarks and post comments. Legacy posts/*/likes, posts/*/bookmarks, and posts/*/reposts are not authority.",
  }),
  defineProjection({
    projectionName: "post_stats",
    classification: "compatibility_projection",
    authoritySources: ["post_engagement_stats"],
    projectionCollections: ["post_stats", "posts.counters"],
    maintainer: "hybrid",
    currentConsumers: ["legacy registry compatibility"],
    currentCertificationStatus: "deprecated",
    requiredCertificationStatus: "deprecated",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["post_stats(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/PostEngagementRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Deprecated alias retained for registry continuity; certification authority is post_engagement_stats.",
  }),
  defineProjection({
    projectionName: "runtime_health_projection",
    classification: "operational_projection",
    authoritySources: ["recordOperationalMetric calls"],
    projectionCollections: [
      "operational_metrics",
      "runtime_health_projection",
      "beta_observability_summary",
    ],
    maintainer: "hybrid",
    currentConsumers: ["operational dashboard"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["runtime_health_projection(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/RuntimeHealthProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta operational recovery from retained operational metrics.",
  }),
  defineProjection({
    projectionName: "runtime_anomaly_projection",
    classification: "operational_projection",
    authoritySources: ["operational_metrics"],
    projectionCollections: ["runtime_anomaly_projection", "runtime_anomaly_events"],
    maintainer: "hybrid",
    currentConsumers: ["operational dashboard"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["runtime_anomaly_projection(updatedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/RuntimeAnomalyProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta operational recovery with bounded anomaly verification.",
  }),
  defineProjection({
    projectionName: "post_analytics",
    classification: "aggregate_projection",
    authoritySources: ["activity_log", "post_analytics/{postId}/viewers"],
    projectionCollections: ["post_analytics"],
    maintainer: "hybrid",
    currentConsumers: ["analytics", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "posts(__name__)",
      "activity_log(object.entity_type,object.entity_id,verb)",
      "post_analytics/{postId}/viewers(__name__)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/PostAnalyticsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Post analytics engagement counters are rebuilt from activity_log and unique viewers from post_analytics/{postId}/viewers; non-unique views are preserved because no replayable event authority exists.",
  }),
  defineProjection({
    projectionName: "activity_log_notifications",
    classification: "fanout_projection",
    authoritySources: ["activity_log"],
    projectionCollections: ["notifications"],
    maintainer: "hybrid",
    currentConsumers: ["notifications", "analytics"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "activity_log(__name__)",
      "activity_log(context.target_owner_uid,__name__)",
      "activity_log(context.target_owner_uid,actor.uid,object.entity_id,verb)",
      "notifications(dedupeId)",
      "notifications(uid)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/ActivityLogNotificationsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Notification fanout is certified as a rebuildable projection from activity_log through recoverActivityLogNotifications.",
  }),
  defineProjection({
    projectionName: "public_profile_counters",
    classification: "aggregate_projection",
    authoritySources: [
      "users/{targetUid}/followers/{followerUid}",
      "users/{followerUid}/following/{targetUid}",
    ],
    projectionCollections: ["public_profiles.followerCount", "public_profiles.followingCount"],
    maintainer: "hybrid",
    currentConsumers: ["profile UI", "search"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "users(__name__)",
      "users/{uid}/followers(__name__)",
      "users/{uid}/following(__name__)",
      "public_profiles(__name__)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/FollowGraphRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Public profile counters are trigger-maintained on normal writes and recovered by recomputing counts from the canonical follow graph.",
  }),
  defineProjection({
    projectionName: "shelf_display_projection",
    classification: "compatibility_projection",
    authoritySources: ["shelf_books"],
    projectionCollections: ["shelf DTOs", "legacy shelf display fields"],
    maintainer: "hybrid",
    currentConsumers: ["shelf UI", "profile shelves"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["shelf_books(ownerId,shelfId,addedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/ShelfDisplayProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as shelf_books-backed DTO compatibility projection without changing library UX.",
  }),
  defineProjection({
    projectionName: "reading_progress_compatibility_fields",
    classification: "compatibility_projection",
    authoritySources: ["reading_progress"],
    projectionCollections: ["reading_progress"],
    maintainer: "hybrid",
    currentConsumers: ["reader insights", "continue reading", "shelf status"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reading_progress(uid,status_state,lastActiveAt)"],
    runbookPath: `${RUNBOOK_ROOT}/ReadingProgressCompatibilityRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta recovery with bounded reading_progress verification and checkpointed repair.",
  }),
  defineProjection({
    projectionName: "reader_insights_dto",
    classification: "compatibility_projection",
    authoritySources: ["reading_progress", "reader_events"],
    projectionCollections: ["callable response only"],
    maintainer: "manual_rebuild",
    currentConsumers: ["Home", "Read continue reading"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: [
      "reading_progress(uid,status_state,lastActiveAt)",
      "reader_events(uid,event,occurredAt)",
    ],
    runbookPath: `${RUNBOOK_ROOT}/ReaderInsightsDtoRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "DTO-only projection certified through bounded query-health verification from reading_progress and reader_events.",
  }),
  defineProjection({
    projectionName: "reader_manifests",
    classification: "media_derivative_projection",
    authoritySources: ["readable book attachment", "storage object"],
    projectionCollections: ["reader_manifests"],
    maintainer: "hybrid",
    currentConsumers: ["reader bootstrap"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_manifests(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderManifestsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta recovery with bounded manifest verification and failure ledger integration.",
  }),
  defineProjection({
    projectionName: "reader_epub_indexes",
    classification: "media_derivative_projection",
    authoritySources: ["EPUB storage object"],
    projectionCollections: [
      "reader_location_map",
      "reader_spine_map",
      "reader_section_graph",
      "reader_stable_anchor_map",
      "reader_navigation_index",
      "reader_pagination_hints",
      "reader_literary_coordinate_map",
      "reader_passage_index",
      "reader_annotation_identity_index",
      "reader_literary_memory_primitives",
    ],
    maintainer: "hybrid",
    currentConsumers: ["reader runtime", "quote anchoring", "highlight anchoring"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_* indexes by __name__"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderEpubIndexesRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta recovery with bounded index verification and checkpoint support.",
  }),
  defineProjection({
    projectionName: "reader_highlights_bookmarks",
    classification: "compatibility_projection",
    authoritySources: ["reader sync operations"],
    projectionCollections: ["reader_highlights", "reader_bookmarks"],
    maintainer: "hybrid",
    currentConsumers: ["reader UI", "profile", "admin merge cleanup"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_highlights(uid,bookId)", "reader_bookmarks(uid,bookId)"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderHighlightsBookmarksRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as authority-adjacent reader user-data projection with bounded verification and no reader UX changes.",
  }),
  defineProjection({
    projectionName: "reader_events",
    classification: "operational_projection",
    authoritySources: ["reader operations"],
    projectionCollections: ["reader_events"],
    maintainer: "hybrid",
    currentConsumers: ["streaks", "diagnostics", "analytics"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_events(uid,event,occurredAt)"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderEventsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as operational reader event projection with bounded retention verification.",
  }),
  defineProjection({
    projectionName: "reader_sync_idempotency",
    classification: "operational_projection",
    authoritySources: ["reader sync calls"],
    projectionCollections: ["reader_sync_idempotency"],
    maintainer: "hybrid",
    currentConsumers: ["reader replay safety"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_sync_idempotency(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderSyncIdempotencyRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as operational replay-safety projection with bounded verification, health, and ledger support.",
  }),
  defineProjection({
    projectionName: "reader_audit_diagnostics",
    classification: "operational_projection",
    authoritySources: ["reader runtime events", "reader diagnostic records", "reader operational logs"],
    projectionCollections: ["reader_audit"],
    maintainer: "hybrid",
    currentConsumers: ["ops", "debug"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["reader_events(__name__)", "reader_events(uid,__name__)", "reader_audit(uid,__name__)"],
    runbookPath: "docs/operations/projections/ReaderAuditDiagnosticsRecoveryRunbook.md",
    recoveryGaps: [],
    notes: "Certified as an operational projection from persisted reader_events into reader_audit; log-only diagnostics remain non-authoritative operational evidence.",
  }),
  defineProjection({
    projectionName: "attachment_metadata",
    classification: "media_derivative_projection",
    authoritySources: ["upload intent", "storage object"],
    projectionCollections: ["attachments"],
    maintainer: "hybrid",
    currentConsumers: ["social composer", "feed rendering", "media URLs"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["attachments(processingStatus,updatedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/AttachmentMetadataRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Phase 8A.20 media recovery without changing upload or storage behavior.",
  }),
  defineProjection({
    projectionName: "attachment_image_derivatives",
    classification: "media_derivative_projection",
    authoritySources: ["original image storage object"],
    projectionCollections: ["storage derivative files", "attachments.renditions"],
    maintainer: "trigger",
    currentConsumers: ["feed rendering", "media rendering"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["attachments(processingStatus,updatedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/AttachmentImageDerivativesRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Phase 8A.20 media recovery with bounded derivative verification.",
  }),
  defineProjection({
    projectionName: "attachment_cleanup_counters",
    classification: "aggregate_projection",
    authoritySources: ["attachments", "attachment_metadata"],
    projectionCollections: ["user_stats.storageUsageBytes", "user_stats.attachmentStorageFiles"],
    maintainer: "hybrid",
    currentConsumers: ["user stats", "admin"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "user_stats(__name__)", "attachments(uploader.uid)"],
    runbookPath: `${RUNBOOK_ROOT}/AttachmentCleanupCountersRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Cleanup counters are certified through exact aggregate recompute from attachments via recoverAttachmentCleanupCounters.",
  }),
  defineProjection({
    projectionName: "cover_derivatives",
    classification: "media_derivative_projection",
    authoritySources: ["books", "external cover sources", "user cover sources"],
    projectionCollections: ["cover_jobs", "book cover fields", "storage covers"],
    maintainer: "hybrid",
    currentConsumers: ["catalog cards", "search"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["cover_jobs(status,updatedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/CoverDerivativesRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Phase 8A.20 media recovery without changing cover UX or pipeline behavior.",
  }),
  defineProjection({
    projectionName: "book_search_fields",
    classification: "search_projection",
    authoritySources: ["books", "editions"],
    projectionCollections: ["books.search", "editions.search"],
    maintainer: "hybrid",
    currentConsumers: ["book search engine"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["books(__name__)", "editions(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/BookSearchFieldsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta recovery with bounded book search field verification.",
  }),
  defineProjection({
    projectionName: "reader_authority_projection",
    classification: "compatibility_projection",
    authoritySources: ["book attachments", "edition attachments", "rights"],
    projectionCollections: ["books.readerAuthority", "editions readability fields"],
    maintainer: "hybrid",
    currentConsumers: ["search results", "reader entry"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["books(__name__)", "editions(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/ReaderAuthorityProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta recovery; readerAuthority remains the certified readability projection.",
  }),
  defineProjection({
    projectionName: "compatibility_readability_fields",
    classification: "compatibility_projection",
    authoritySources: ["readerAuthority", "readable attachment evidence"],
    projectionCollections: ["books.downloadable", "books.isEbookAvailable"],
    maintainer: "hybrid",
    currentConsumers: ["legacy client", "search DTOs"],
    currentCertificationStatus: "deprecated",
    requiredCertificationStatus: "deprecated",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["books(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/CompatibilityReadabilityFieldsDeprecationRunbook.md`,
    recoveryGaps: [],
    notes: "Deprecated behind certified reader_authority_projection; maintained only for legacy compatibility until removal.",
  }),
  defineProjection({
    projectionName: "catalog_identity_projection",
    classification: "compatibility_projection",
    authoritySources: ["canonical ingestion", "materialization"],
    projectionCollections: ["book_identity", "author_identity", "canonical keys"],
    maintainer: "hybrid",
    currentConsumers: ["ingestion dedupe", "search"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["book_identity(__name__)", "author_identity(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/CatalogIdentityProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as canonical ingestion/materialization identity projection without discovery algorithm changes.",
  }),
  defineProjection({
    projectionName: "authored_author_link_projection",
    classification: "fanout_projection",
    authoritySources: ["users", "public_profiles", "authors"],
    projectionCollections: ["author_user_links", "authored author fields"],
    maintainer: "hybrid",
    currentConsumers: ["author catalog", "profile"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["author_user_links(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/AuthoredAuthorLinkProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as user/public_profile/author fanout projection without author catalog UX changes.",
  }),
  defineProjection({
    projectionName: "social_post_render_projection",
    classification: "fanout_projection",
    authoritySources: ["posts", "books", "authors", "quotes", "shelves"],
    projectionCollections: ["posts.renderProjection", "attachment snapshot fields"],
    maintainer: "hybrid",
    currentConsumers: ["social feed read path"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["posts(__name__)", "books(__name__)", "authors(__name__)", "social_quote_projection(__name__)", "shelves(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/SocialPostRenderProjectionRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Embedded render snapshots are certified as rebuildable projections from post content and attached entity authorities.",
  }),
  defineProjection({
    projectionName: "projected_viewer_state",
    classification: "fanout_projection",
    authoritySources: ["users/{uid}/likes", "users/{uid}/bookmarks", "users/{uid}/reposts"],
    projectionCollections: ["users/{uid}/post_interaction_state"],
    maintainer: "hybrid",
    currentConsumers: ["feed optimization"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["users(__name__)", "users/{uid}/likes(__name__)", "users/{uid}/bookmarks(type,__name__)", "users/{uid}/reposts(__name__)", "users/{uid}/post_interaction_state(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/ProjectedViewerStateRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Viewer state is certified as rebuildable optimization state from canonical likes, bookmarks, and reposts.",
  }),
  defineProjection({
    projectionName: "system_metrics",
    classification: "operational_projection",
    authoritySources: ["metric events", "trigger calls"],
    projectionCollections: ["system_metrics", "system_metrics_daily"],
    maintainer: "hybrid",
    currentConsumers: ["admin dashboard", "daily export"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["system_metrics_daily(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/SystemMetricsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as an operational metric projection with bounded dry-run verification and event replay boundaries documented through recoverTier1PublicBetaProjection.",
  }),
  defineProjection({
    projectionName: "system_events",
    classification: "operational_projection",
    authoritySources: ["structured app events"],
    projectionCollections: ["system_events"],
    maintainer: "hybrid",
    currentConsumers: ["admin event views", "analytics export"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["system_events(createdAt)"],
    runbookPath: `${RUNBOOK_ROOT}/SystemEventsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as append-only operational event evidence with bounded dry-run verification, retention guardrails, and event replay procedures.",
  }),
  defineProjection({
    projectionName: "analytics_daily_exports",
    classification: "operational_projection",
    authoritySources: ["system_metrics", "system_metrics_daily", "system_events"],
    projectionCollections: ["analytics_exports"],
    maintainer: "hybrid",
    currentConsumers: ["admin", "reporting"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["system_metrics_daily(__name__)", "system_events(__name__)"],
    runbookPath: `${RUNBOOK_ROOT}/AnalyticsDailyExportsRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Scheduled analytics exports are certified with date-targeted rerun support through recoverAnalyticsDailyExports.",
  }),
  defineProjection({
    projectionName: "intelligence_signal_queue",
    classification: "operational_projection",
    authoritySources: ["user activity", "reader signals", "write signals", "social signals"],
    projectionCollections: ["intelligence_signal_queue"],
    maintainer: "hybrid",
    currentConsumers: ["admin intelligence", "personalization"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["intelligence signals by status/update time"],
    runbookPath: `${RUNBOOK_ROOT}/IntelligenceSignalQueueRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified as the existing intelligence signal queue with bounded verification and replay boundaries; AI, matchmaker, and recommendation behavior are unchanged.",
  }),
  defineProjection({
    projectionName: "intelligence_aggregates",
    classification: "aggregate_projection",
    authoritySources: ["intelligence signals"],
    projectionCollections: ["user_intelligence_profiles", "intelligence_aggregates_global"],
    maintainer: "scheduled_job",
    currentConsumers: ["admin intelligence dashboard"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["intelligence aggregates by uid/update time"],
    runbookPath: `${RUNBOOK_ROOT}/IntelligenceAggregatesRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified over existing profile and global aggregate collections with checkpointed verification; recommendation and matchmaker scoring behavior is unchanged.",
  }),
  defineProjection({
    projectionName: "deletion_cascade_cleanup_projection",
    classification: "operational_projection",
    authoritySources: ["deletion requests", "authority docs"],
    projectionCollections: ["cascade-deleted projection docs"],
    maintainer: "hybrid",
    currentConsumers: ["privacy", "admin compliance"],
    currentCertificationStatus: "production_ready",
    rebuildSupported: true,
    verificationSupported: true,
    reconciliationSupported: true,
    failureLedgerSupported: true,
    dryRunSupported: true,
    checkpointSupported: true,
    structuredReportingSupported: true,
    idempotent: true,
    restartable: true,
    requiredIndexes: ["deletion_requests(status,updatedAt)"],
    runbookPath: `${RUNBOOK_ROOT}/DeletionCascadeCleanupRecoveryRunbook.md`,
    recoveryGaps: [],
    notes: "Certified through Tier 1 public-beta evidence verification for deletion request cleanup projections.",
  }),
];

export const PROJECTION_DEFINITIONS: ProjectionDefinition[] =
  PROJECTION_REGISTRY_ENTRIES;

const PROJECTION_BY_NAME = new Map(
  PROJECTION_REGISTRY_ENTRIES.map((definition) => [
    definition.projectionName,
    definition,
  ])
);

export function listProjectionDefinitions(): RegisteredProjectionDefinition[] {
  return [...PROJECTION_REGISTRY_ENTRIES];
}

export function getProjectionDefinition(
  projectionName: string
): RegisteredProjectionDefinition | null {
  return PROJECTION_BY_NAME.get(projectionName) ?? null;
}

export function requireProjectionDefinition(
  projectionName: string
): RegisteredProjectionDefinition {
  const definition = getProjectionDefinition(projectionName);
  if (!definition) {
    throw new Error(`Unknown projection: ${projectionName}`);
  }
  return definition;
}

export function isRegisteredProjectionName(projectionName: string): boolean {
  return PROJECTION_BY_NAME.has(projectionName);
}

export function listProjectionDefinitionsByStatus(
  status: ProjectionCertificationStatus
): RegisteredProjectionDefinition[] {
  return PROJECTION_REGISTRY_ENTRIES.filter(
    (definition) => definition.currentCertificationStatus === status
  );
}

export function listProjectionDefinitionsByClassification(
  classification: ProjectionClassification
): RegisteredProjectionDefinition[] {
  return PROJECTION_REGISTRY_ENTRIES.filter(
    (definition) => definition.classification === classification
  );
}

export function getProjectionHealthDocumentId(projectionName: string): string {
  return requireProjectionDefinition(projectionName).projectionName;
}

export function createUnknownProjectionHealth(
  projectionName: string,
  checkedAtIso: string
): ProjectionHealth {
  const definition = requireProjectionDefinition(projectionName);
  return {
    projectionName: definition.projectionName,
    status: "unknown",
    productionStatus: definition.currentCertificationStatus,
    lastSuccessfulRebuildAtIso: null,
    lastSuccessfulReconcileAtIso: null,
    lastVerificationAtIso: null,
    lastFailureAtIso: null,
    pendingFailures: 0,
    deadLetterFailures: 0,
    driftDetected: 0,
    driftRepaired: 0,
    staleProjectionCount: 0,
    missingProjectionCount: 0,
    checkedAtIso,
  };
}

export function generateProjectionCertificationReport(
  definitions: RegisteredProjectionDefinition[] = PROJECTION_REGISTRY_ENTRIES
): ProjectionCertificationReport {
  const statusBreakdown: Record<ProjectionCertificationStatus, number> = {
    not_ready: 0,
    beta_ready: 0,
    production_ready: 0,
    deprecated: 0,
  };
  const productionReady: string[] = [];
  const betaReady: string[] = [];
  const notReady: string[] = [];
  const deprecated: string[] = [];
  const failingProductionRequired: ProjectionCertificationGateResult[] = [];
  const gapMap = new Map<string, Set<string>>();

  for (const definition of definitions) {
    statusBreakdown[definition.currentCertificationStatus] += 1;

    if (definition.currentCertificationStatus === "production_ready") {
      productionReady.push(definition.projectionName);
    } else if (definition.currentCertificationStatus === "beta_ready") {
      betaReady.push(definition.projectionName);
    } else if (definition.currentCertificationStatus === "deprecated") {
      deprecated.push(definition.projectionName);
    } else {
      notReady.push(definition.projectionName);
    }

    const gateResult = evaluateProjectionCertification(definition);
    if (
      definition.requiredCertificationStatus === "production_ready" &&
      !gateResult.passed
    ) {
      failingProductionRequired.push(gateResult);
    }

    for (const gap of [
      ...definition.recoveryGaps,
      ...gateResult.missingRequirements,
    ]) {
      const projections = gapMap.get(gap) ?? new Set<string>();
      projections.add(definition.projectionName);
      gapMap.set(gap, projections);
    }
  }

  const topRemainingGaps = [...gapMap.entries()]
    .map(([requirement, projections]) => ({
      requirement,
      count: projections.size,
      projections: [...projections].sort(),
    }))
    .sort((a, b) => b.count - a.count || a.requirement.localeCompare(b.requirement))
    .slice(0, 20);

  return {
    total: definitions.length,
    statusBreakdown,
    productionReady: productionReady.sort(),
    betaReady: betaReady.sort(),
    notReady: notReady.sort(),
    deprecated: deprecated.sort(),
    failingProductionRequired,
    topRemainingGaps,
  };
}

export const PROJECTION_CERTIFICATION_REPORT =
  generateProjectionCertificationReport();
